FROM openjdk:8-jdk-alpine
#EXPOSE 8082:8082
ADD target/chefsick-service-cart-1.0-SNAPSHOT.jar chefsick-service-cart-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "chefsick-service-cart-1.0-SNAPSHOT.jar"]